# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# THE CLOSURE IS IN THE BUNDLE, except where a module is already a port.
# `pypackages` names the rest of khard's runtime set and `ports/fetch` crawls
# each tarball's own build-system.requires from there, so one bundle carries
# what four more recipes would. python-dateutil and six come from their
# python3-* ports: a second copy in site-packages would be a path two packages
# own, and kpkg refuses that as a conflict.
#
# vobject IS PINNED BELOW ITS LATEST. 0.9.9's setup.cfg reads its version with
# `attr: vobject.VERSION`, which the package re-exports from a submodule that
# imports dateutil — so setuptools has to IMPORT vobject to learn its version,
# and in the isolated environment a source-only download builds metadata in,
# dateutil is not there. The download fails with `vobject has no attribute
# VERSION`. khard asks for `~= 0.9.7`, and 0.9.8 reads statically.
mkdir -p vendor
tar -xf $PORT_SRC/$name-vendor-$version.tar.xz --strip-components=1 -C vendor

# Backends into the build root, not into $PKG, and in bootstrap order — see
# ports/core/khal/build.sh, which does the same for the same reason.
pyb() { pip3 install --no-index --find-links=vendor --no-build-isolation "$@"; }
pyb flit-core
pyb packaging
# BEFORE setuptools-scm, which imports it while its own metadata is generated:
# setuptools-scm 10 is split in two and names vcs-versioning in its build-system
# requires. `--no-build-isolation` installs none of those, so the order of these
# lines IS the build environment.
pyb vcs-versioning
pyb setuptools-scm

pip3 install --no-deps --no-index --find-links=vendor --no-build-isolation \
	--root=$PKG --prefix=/usr \
	configobj pytz ruamel.yaml vobject .

# THE MANUAL PAGES ARE GENERATED BY SPHINX FROM doc/source: khard(1) and
# khard-subcommands(1) are drawn from khard's own argument parser by
# sphinx-argparse, which python3-sphinx carries, and khard.conf(5) is written
# out. conf.py imports khard from the source tree; its dependencies come from
# the staged package. `-D extensions` replaces the list conf.py sets, leaving
# out sphinx-autoapi, which renders the API reference of the web site and is
# not a port.
_site=$(python3 -c 'import sys, sysconfig; print(sysconfig.get_path("purelib", vars={"base": sys.argv[1]}))' "$PKG/usr")
(cd doc/source && PYTHONPATH=$_site sphinx-build -b man -q \
	-D extensions=sphinx.ext.autodoc,sphinx.ext.autosectionlabel,sphinx.ext.todo,sphinxarg.ext \
	-d "$SRC_ROOT/khard-doctrees" . "$SRC_ROOT/khard-man")
install -Dm644 "$SRC_ROOT"/khard-man/*.1 -t "$PKG/usr/share/man/man1"
install -Dm644 "$SRC_ROOT"/khard-man/*.5 -t "$PKG/usr/share/man/man5"

# NO DESKTOP ENTRY. khard is a command that prints and exits — `khard list`,
# `khard show` — with no screen of its own to put a menu row in front of, and
# an entry that opened a terminal to print one page and close it would be a
# row that looks broken. aerc reaches it as a completion source instead.
