# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# THE CLOSURE IS IN THE BUNDLE, except where a module is already a port, and
# this one is not pure python. certifi, charset-normalizer, click, click-log,
# idna, requests, typing-extensions and urllib3 come from their python3-* ports:
# a second copy in site-packages would be a path two packages own, and kpkg
# refuses that as a conflict. Five of the bundled dependencies carry C —
# aiohttp (which vendors llhttp), frozenlist, multidict, propcache and yarl — so
# this port needs a compiler on the target, which every phase-4 port has.
#
# THREE OF THEM BUILD THROUGH AN IN-TREE PEP 517 BACKEND. frozenlist, propcache
# and yarl declare `build-backend = pep517_backend.hooks`, which lives inside
# their own sdists and needs `expandvars`, and that backend compiles the
# accelerated modules with Cython; aiohttp additionally wants `pkgconfig`.
# Cython and pkgconfig are ports.
mkdir -p vendor
tar -xf $PORT_SRC/$name-vendor-$version.tar.xz --strip-components=1 -C vendor

# BUILD ISOLATION IS OFF, so each sdist builds with the backend already
# installed. setuptools, setuptools-scm, hatchling, hatch-vcs, poetry-core,
# pkgconfig and Cython are ports in `depends`. expandvars and hatch-fancy-pypi-readme are
# not, and are backends of this bundle alone, so they are installed from it
# into the build root, not into $PKG — a backend is what compiles a wheel, not
# something the image runs. --break-system-packages because python3 marks its
# site-packages as kpkg's (PEP 668), and an install into the build root is
# exactly what that marker refuses.
pip3 install --no-index --find-links=vendor --no-build-isolation \
	--break-system-packages expandvars hatch-fancy-pypi-readme

pip3 install --no-deps --no-index --find-links=vendor --no-build-isolation \
	--root=$PKG --prefix=/usr \
	aiohappyeyeballs aiohttp aiosignal aiostream attrs \
	frozenlist multidict propcache tenacity yarl .

# THE MANUAL PAGE IS GENERATED BY SPHINX FROM docs/: man_pages in conf.py makes
# the whole manual one vdirsyncer(1). conf.py imports vdirsyncer, so the staged
# package goes on the path.
_site=$(python3 -c 'import sys, sysconfig; print(sysconfig.get_path("purelib", vars={"base": sys.argv[1]}))' "$PKG/usr")
(cd docs && PYTHONPATH=$_site sphinx-build -b man -q \
	-d "$SRC_ROOT/vdirsyncer-doctrees" . "$SRC_ROOT/vdirsyncer-man")
install -Dm644 "$SRC_ROOT/vdirsyncer-man/vdirsyncer.1" -t "$PKG/usr/share/man/man1"

# NO DESKTOP ENTRY. vdirsyncer is a command a person runs or a timer does —
# `vdirsyncer sync` — with no screen to put a menu row in front of.
