#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

mkdir -p build && cd build
# GDAL_USE_CURL=OFF for PROJ's reason: /vsicurl/ turns a dataset path into an
# HTTP client, and a format library that reaches the network is a format
# library that fails differently depending on who is listening. Everything here
# reads from disk.
#
# No python bindings — the numeric ring's python stack is its own work and
# gdal's binding is generated by SWIG against it.
cmake .. -G Ninja -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib \
	-DGDAL_USE_CURL=OFF \
	-DBUILD_PYTHON_BINDINGS=OFF \
	-DBUILD_JAVA_BINDINGS=OFF \
	-DBUILD_CSHARP_BINDINGS=OFF \
	-DBUILD_TESTING=OFF \
	-DGDAL_USE_EXTERNAL_LIBS=ON
ninja
DESTDIR=$PKG ninja install
