#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# The drive layer under every optical-media consumer here: mpv's cdda://,
# gst-plugins-ugly's cdiocddasrc, mpd's cdio_paranoia input and its iso9660
# archive plugin, and libcdio-paranoia on top of it. The cd-info, cd-drive,
# cd-read, iso-info, iso-read and cdda-player programs come with it; their
# manual pages are regenerated by help2man from the built programs.
#
# CDDB lookups need libcddb and VCD details need libvcdinfo, neither a port.
./configure --prefix=/usr --libdir=/usr/lib --disable-static \
	--disable-cddb \
	--disable-vcd-info \
	--disable-example-progs \
	--disable-cpp-progs
make
make DESTDIR=$PKG install
