#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# Pinned to 0.20.2 and vendored: wlroots breaks API on every release, and the
# repo builds --network none anyway, so an upgrade has to be a deliberate act
# rather than something that happens to a build.
#
# The releases/ download URL 403s; /-/archive/ is the one that works.
#
# backends: drm and libinput are the real hardware path. `headless` is NOT a
# choice here — meson only accepts auto/drm/libinput/x11 and builds the
# headless backend unconditionally (backend/meson.build subdir's it), so
# naming it fails configure outright. It is still available at runtime via
# WLR_BACKENDS=headless, which is what makes a GPU-less screenshot test
# possible. x11 is dropped: it exists to nest a compositor inside an X
# session, and KDOS has no X server.
#
# renderers: gles2 for the CRT shader path, vulkan because 0.20's
# color-management support is Vulkan-first. `pixman` is NOT a choice here
# either — meson accepts only auto/gles2/vulkan and builds the pixman
# renderer unconditionally. It is selected at runtime with WLR_RENDERER=pixman,
# and it is what lets a plain `make run` (virtio-vga, no virgl) bring a
# session up at all: smithay refused software EGL, which is why COSMIC never
# had that. kdos-desktop sets it when there is no +resource_blob.
#
# color-management is ON and is lcms2: it is what turns an output's ICC
# profile into the transform the renderer applies. Left at `auto`, a missing
# lcms2 drops ICC support without a word; enabled, it stops configure.
#
# allocators are named for the same reason: `auto` probes gbm and udmabuf and
# keeps whichever it finds, so a missing gbm would leave a compositor that
# cannot allocate a scanout buffer on real hardware.

# A CAPTURE OF AN IDLE SCREEN HAS TO BE ANSWERED. There is no build flag for
# it: ext-image-copy-capture forces an output commit only where the session
# already has damage, which makes a recording of a still desktop one frame
# long. The patch beside this file states the rest.
patch -p1 -i "$PORT_SRC/idle-capture-frame.patch"

meson setup build \
	--prefix=/usr \
	--libdir=lib \
	--buildtype=release \
	-Dexamples=false \
	-Dbackends=drm,libinput \
	-Drenderers=gles2,vulkan \
	-Dallocators=gbm,udmabuf \
	-Dsession=enabled \
	-Dxwayland=enabled \
	-Dcolor-management=enabled \
	-Dlibliftoff=disabled \
	-Dxcb-errors=disabled

meson compile -C build
DESTDIR=$PKG meson install --no-rebuild -C build

# wlroots' own protocol XML, which upstream does NOT install.
#
# wlr_layer_shell_v1.h includes "wlr-layer-shell-unstable-v1-protocol.h", a
# header generated by wayland-scanner that is not shipped either — so any
# consumer of layer-shell must run the scanner over the XML itself, and every
# wlroots compositor either vendors a copy of the file or digs it out of this
# tarball. Installing it here gives kdos-comp one stable path to point at and
# keeps a single copy of a protocol definition in the tree.
install -d "$PKG/usr/share/wlroots/protocols"
install -m644 protocol/*.xml "$PKG/usr/share/wlroots/protocols/"
