/*
 * KK — the KDOS demo.  genface: bake face/face.txt into src/kd[1-4].c
 *
 * HOST-ONLY. Nothing on the target and nothing in the build ever runs this —
 * the four generated .c files are committed, exactly like kdos-icons' marks
 * and kdos-splash's logo.txt. Run it by hand when the portrait changes:
 *
 *     cc -O2 -I../src -o genface genface.c ../src/minilzo.c
 *     ./genface ../face/face.txt ../src
 *
 * What it produces is BB's own `struct image`: raw 8-bit greyscale,
 * LZO1X-compressed, as a C array. Keeping that format means image.c's
 * lzo1x_decompress path is untouched and the portrait travels through exactly
 * the same scaler the 1997 ones did.
 *
 * Two things about the geometry, both of which show immediately if they are
 * wrong. A character cell is about twice as tall as it is wide, so the 85x52
 * grid represents roughly 85x104 square pixels — reconstructing it 1:1 gives a
 * face squashed flat. And the grid is coarse enough that nearest-neighbour
 * upscaling reads as a mosaic, so the doubling is bilinear.
 *
 * The four frames are the crystallise stages the profile card animates: rain
 * condensing into the portrait, at roughly a quarter, half, three quarters and
 * fully formed. vezen() steps through them 0.5s apart, so what the viewer sees
 * is the face assembling out of noise rather than four photographs.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "minilzo.h"

#define LVL "0123456789ABCDEFGHIJKLMNOP"
#define NLVL 26

#define MAXROW 256
#define MAXCOL 256

static int rows, cols;
static unsigned char grid[MAXROW][MAXCOL];	/* 0..255 per cell */

/* Deterministic per-cell noise. A cell's "arrival time" in the crystallise is
 * fixed by its position, so every frame agrees about which cells are already
 * formed — with rand() the four frames would each dissolve a different set and
 * the sequence would look like static, not like assembly. */
static unsigned int cell_hash(int x, int y)
{
	unsigned int h = (unsigned int)(x * 73856093) ^ (unsigned int)(y * 19349663);

	h ^= h >> 13;
	h *= 0x5bd1e995u;
	h ^= h >> 15;
	return h;
}

static int read_face(const char *path)
{
	char line[1024];
	FILE *f = fopen(path, "r");

	if (!f) {
		perror(path);
		return -1;
	}
	while (fgets(line, sizeof(line), f)) {
		char *tab;
		int x;

		if (line[0] == '#' || line[0] == '\n')
			continue;
		tab = strchr(line, '\t');
		if (!tab)
			continue;
		tab++;
		for (x = 0; tab[x] && tab[x] != '\n' && x < MAXCOL; x++) {
			const char *p = strchr(LVL, tab[x]);
			int lvl = p ? (int)(p - LVL) : 0;

			grid[rows][x] = (unsigned char)(lvl * 255 / (NLVL - 1));
		}
		if (x > cols)
			cols = x;
		if (++rows >= MAXROW)
			break;
	}
	fclose(f);
	return rows ? 0 : -1;
}

/* Bilinear sample of the cell grid, in a space where one grid row is two grid
 * columns tall — that is the cell aspect correction. */
static unsigned char sample(double gx, double gy)
{
	int x0, y0, x1, y1;
	double fx, fy, a, b;

	if (gx < 0) gx = 0;
	if (gy < 0) gy = 0;
	if (gx > cols - 1) gx = cols - 1;
	if (gy > rows - 1) gy = rows - 1;
	x0 = (int)gx; y0 = (int)gy;
	x1 = x0 + 1 < cols ? x0 + 1 : x0;
	y1 = y0 + 1 < rows ? y0 + 1 : y0;
	fx = gx - x0; fy = gy - y0;
	a = grid[y0][x0] * (1 - fx) + grid[y0][x1] * fx;
	b = grid[y1][x0] * (1 - fx) + grid[y1][x1] * fx;
	return (unsigned char)(a * (1 - fy) + b * fy + 0.5);
}

static void emit(const char *dir, const char *name, const unsigned char *raw,
		 int w, int h)
{
	static unsigned char wrkmem[LZO1X_MEM_COMPRESS];
	unsigned char *comp;
	lzo_uint clen = 0;
	char path[512];
	FILE *f;
	lzo_uint i;

	comp = malloc((size_t)w * h + (size_t)w * h / 16 + 64 + 3);
	if (lzo1x_1_compress(raw, (lzo_uint)(w * h), comp, &clen, wrkmem) != LZO_E_OK) {
		fprintf(stderr, "genface: compression failed\n");
		exit(1);
	}

	/* Prove the demo can read back what we just wrote, here rather than on
	 * a TTY: image.c exits the whole program on a bad decompress. */
	{
		unsigned char *back = malloc((size_t)w * h + 8);
		lzo_uint blen = (lzo_uint)(w * h);

		if (lzo1x_decompress(comp, clen, back, &blen, NULL) != LZO_E_OK ||
		    blen != (lzo_uint)(w * h) || memcmp(back, raw, (size_t)w * h)) {
			fprintf(stderr, "genface: %s does not round-trip\n", name);
			exit(1);
		}
		free(back);
	}

	snprintf(path, sizeof(path), "%s/%s.c", dir, name);
	f = fopen(path, "w");
	if (!f) {
		perror(path);
		exit(1);
	}
	fprintf(f,
		"/*\n"
		" * KK — the KDOS demo.  GENERATED by tools/genface.c from\n"
		" * face/face.txt; do not edit. Frame %c of the portrait\n"
		" * crystallise, %dx%d greyscale, LZO1X.\n"
		" */\n\n"
		"#include \"image.h\"\n\n"
		"static unsigned char %sdata[] = {",
		name[2], w, h, name);
	for (i = 0; i < clen; i++)
		fprintf(f, "%s%u,", (i % 16) ? " " : "\n\t", comp[i]);
	fprintf(f, "\n};\n\nstruct image %s = { %sdata, %lu, %d, %d };\n",
		name, name, (unsigned long)clen, w, h);
	fclose(f);
	printf("%-8s %dx%d  %lu -> %lu bytes\n", name, w, h,
	       (unsigned long)(w * h), (unsigned long)clen);
	free(comp);
}

int main(int argc, char **argv)
{
	const char *in = argc > 1 ? argv[1] : "../face/face.txt";
	const char *out = argc > 2 ? argv[2] : "../src";
	/* 2x the aspect-corrected grid: 85x52 cells -> 170x208 pixels, which
	 * is the size class BB's own portraits were ({145, 200}). */
	int w, h, frame;
	unsigned char *raw;

	if (lzo_init() != LZO_E_OK) {
		fprintf(stderr, "genface: lzo_init failed\n");
		return 1;
	}
	if (read_face(in))
		return 1;

	w = cols * 2;
	h = rows * 4;		/* x2 upscale, x2 again for the cell aspect */
	raw = malloc((size_t)w * h);

	for (frame = 1; frame <= 4; frame++) {
		/* How much of the picture has condensed, per frame. */
		static const double formed[4] = { 0.25, 0.55, 0.85, 1.0 };
		double f = formed[frame - 1];
		char name[8];
		int x, y;

		for (y = 0; y < h; y++)
			for (x = 0; x < w; x++) {
				double gx = (double)x * (cols - 1) / (w - 1);
				double gy = (double)y * (rows - 1) / (h - 1);
				unsigned char v = sample(gx, gy);
				unsigned int r = cell_hash(x / 2, y / 4);
				double arrive = (double)(r & 0xffff) / 65535.0;

				if (arrive <= f) {
					raw[y * w + x] = v;
				} else {
					/* not yet formed: a falling streak,
					 * brightest at its head */
					int phase = (int)((r >> 16) & 31);
					int lit = ((y / 4 + phase + (int)(f * 40)) % 11) == 0;

					raw[y * w + x] = lit ? 200 : 0;
				}
			}
		snprintf(name, sizeof(name), "kd%d", frame);
		emit(out, name, raw, w, h);
	}
	free(raw);
	return 0;
}
