#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

LIBS="$PORT_SRC/../../libs"

# libkxdg is here for `kdos appid`, which reads installed desktop entries, and
# libkproc for `kdos stutter`'s box identity. Both link libkbase and nothing
# else, so neither costs an external dependency. libkpack (over libksig) is
# `kdos app update`: reading a PACKAGES index and picking the delta is the
# same parser kdos-packd uses, and a second one here would be a second answer
# to what a source offers.
# libpng is the wallpaper retint (`kdos theme` writes the accent-tinted copy
# into ~/.cache); KDOS_HAVE_LIBPNG gates the code so the host selftest, which
# links without libpng, still builds.
gcc $CFLAGS -O2 -std=gnu11 -D_GNU_SOURCE -DKDOS_HAVE_LIBPNG -Wall -Wextra \
	-I"$LIBS/libkbase" -I"$LIBS/libkcolor" -I"$LIBS/libkpkg" \
	-I"$LIBS/libkxdg" -I"$LIBS/libkproc" -I"$LIBS/libksig" \
	-I"$LIBS/libkpack" -I"$PORT_SRC" \
	-o kdos-tools \
	"$PORT_SRC"/*.c \
	"$LIBS"/libkbase/*.c "$LIBS"/libkcolor/*.c "$LIBS"/libkpkg/*.c \
	"$LIBS"/libkxdg/*.c "$LIBS"/libkproc/*.c \
	"$LIBS"/libksig/*.c "$LIBS"/libksig/monocypher/*.c \
	"$LIBS"/libkpack/*.c -lpng $LDFLAGS

install -Dm755 kdos-tools "$PKG/usr/sbin/ksvc"

# Dispatched on its own basename, so every name is a link to the one
# binary. /etc/inittab wraps both gettys in kdos-getty and every
# init.d script reaches ksvc through service_helper.
ln -s ksvc "$PKG/usr/sbin/service"
install -d "$PKG/usr/local/sbin"
ln -s /usr/sbin/ksvc "$PKG/usr/local/sbin/kdos-getty"

install -d "$PKG/usr/local/bin"
for t in kdos kdos-banner kdos-shot kdos-fetch-app kdos-fetch-static kdos-sfx; do
	ln -s /usr/sbin/ksvc "$PKG/usr/local/bin/$t"
done

# kdos-bootctl lands in /usr/bin rather than /usr/local/bin: the initramfs build
# copies it by path, and /usr/local is not somewhere a boot-critical tool should
# have to be looked for.
install -d "$PKG/usr/bin"
ln -s /usr/sbin/ksvc "$PKG/usr/bin/kdos-bootctl"

# The recorded debug cycles, queryable offline by `kdos why`, `kdos explain`
# and `kdos oracle`. Ships in the ISO like the appbox does: a help system that
# needs a network is no help on the machine that will not boot.
install -d "$PKG/usr/share/kdos/reasons"
install -m644 "$PORT_SRC"/reasons/*.txt "$PKG/usr/share/kdos/reasons/"

# The vendored Alpine security database, read by `kdos cve`. 270 KB for 798
# packages, and the whole point is that the answer needs no network — the
# machine that cannot reach a CVE feed is exactly the machine whose owner wants
# to know. Regenerated by hand with secdb/vendor.py.
install -Dm644 "$PORT_SRC/secdb/secdb.txt" "$PKG/usr/share/kdos/secdb.txt"
