#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

tar xf $PORT_SRC/${name}-vendor-${version}.tar.xz

# `rclone gui` embeds a prebuilt web bundle and has no build tag, so the patch
# takes it off the command list; `rcd --rc-web-gui` fetches its GUI at run time
# and embeds nothing. noselfupdate drops `selfupdate`, which downloads a binary
# over the one /usr/bin/rclone the package owns.
patch -p1 -i "$PORT_SRC/no-embedded-gui.patch"

# THE CLOUD BACKENDS ARE DEAD WEIGHT AND THE LOCAL VERBS ARE NOT. What earns
# this a place on an offline machine is `rclone check`, which answers "did
# every byte reach the second stick" in one command over two local trees —
# nothing else here compares two directories by CONTENT and reports what
# differs. `rclone mount` additionally reads an archive as a filesystem; it is
# the pure-Go FUSE client, which runs fuse's setuid fusermount3 to mount, so
# fuse is a dependency and not an accident of the image.
export CGO_ENABLED=0
go build -mod=vendor -tags noselfupdate \
	-ldflags "-s -w -X github.com/rclone/rclone/fs.Version=v$version" -o rclone
install -Dm755 rclone $PKG/usr/bin/rclone
install -Dm644 rclone.1 $PKG/usr/share/man/man1/rclone.1

# The completions are generated by the binary, so they match the commands it
# was built with.
./rclone completion bash - > rclone.bash
./rclone completion zsh - > _rclone
./rclone completion fish - > rclone.fish
install -Dm644 rclone.bash $PKG/usr/share/bash-completion/completions/rclone
install -Dm644 _rclone $PKG/usr/share/zsh/site-functions/_rclone
install -Dm644 rclone.fish $PKG/usr/share/fish/vendor_completions.d/rclone.fish
