#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------


# EVERY OPTIONAL PART IS NAMED. GMP is off upstream by default and on here, so
# the arithmetic theories use the gmp port rather than z3's own bignum code.
# The Python bindings are generated from the same API headers as libz3 and cost
# no extra compile; python3 is needed by the build regardless, because the API
# logging and parameter sources are generated by z3's own Python scripts.
# Java, .NET, OCaml, Julia and Go bindings stay off. The tarball carries no
# .git, and the git-hash options are off so the version string does not depend
# on where the build ran.
mkdir -p build && cd build
cmake .. -G Ninja \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DPython3_EXECUTABLE=/usr/bin/python3 \
	-DZ3_BUILD_LIBZ3_SHARED=ON \
	-DZ3_BUILD_EXECUTABLE=ON \
	-DZ3_BUILD_TEST_EXECUTABLES=OFF \
	-DZ3_ENABLE_EXAMPLE_TARGETS=OFF \
	-DZ3_BUILD_DOCUMENTATION=OFF \
	-DZ3_USE_LIB_GMP=ON \
	-DZ3_BUILD_PYTHON_BINDINGS=ON \
	-DZ3_INSTALL_PYTHON_BINDINGS=ON \
	-DZ3_BUILD_JAVA_BINDINGS=OFF \
	-DZ3_BUILD_DOTNET_BINDINGS=OFF \
	-DZ3_BUILD_OCAML_BINDINGS=OFF \
	-DZ3_BUILD_JULIA_BINDINGS=OFF \
	-DZ3_BUILD_GO_BINDINGS=OFF \
	-DZ3_INCLUDE_GIT_HASH=OFF \
	-DZ3_INCLUDE_GIT_DESCRIBE=OFF
ninja
DESTDIR=$PKG ninja install

# THE BINDINGS' OWN COPY OF libz3 IS A SYMLINK INTO THE BUILD TREE, installed
# as-is, so it dangles on the target. z3core.py falls back to sys.prefix/lib,
# which is where the real library is, so the link is dropped rather than
# repointed.
rm -f "$PKG"/usr/lib/python3*/site-packages/z3/libz3.so*

# z3 ships no manual page; its --help and --version are help2man's input.
install -d "$PKG/usr/share/man/man1"
help2man -N --no-discard-stderr -n 'satisfiability modulo theories solver' \
	-o "$PKG/usr/share/man/man1/z3.1" ./z3
