# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# THE CLOSURE IS IN THE BUNDLE, except where a module is already a port.
# `pypackages` names the part of khal's runtime set that no other program here
# imports. Everything shared — click, click-log, configobj, python-dateutil,
# pytz, six, typing-extensions, urwid, wcwidth — comes from its python3-* port:
# a module two packages each installed would be a path both own, and which of
# them the image kept would follow build order.
mkdir -p vendor
tar -xf $PORT_SRC/$name-vendor-$version.tar.xz --strip-components=1 -C vendor

# BUILD ISOLATION IS OFF, so each sdist builds with the backend already
# installed: setuptools and setuptools-scm for khal, tzdata, tzlocal and pyxdg,
# hatchling and hatch-vcs for icalendar. All four are ports in `depends`, so
# nothing is installed into the build root outside a package.
#
# --no-deps, because the bundle IS the dependency set and pip resolving it
# again would ask the network.
pip3 install --no-deps --no-index --find-links=vendor --no-build-isolation \
	--root=$PKG --prefix=/usr \
	icalendar pyxdg tzdata tzlocal .

# THE MANUAL PAGE IS GENERATED BY SPHINX FROM doc/source, whose conf.py imports
# khal and its configuration spec — so the staged package goes on the path.
# `-D extensions` replaces the list conf.py sets: sphinxfeed writes the web
# site's news feed and is not a port, and intersphinx has no network to load
# its inventory from.
_site=$(python3 -c 'import sys, sysconfig; print(sysconfig.get_path("purelib", vars={"base": sys.argv[1]}))' "$PKG/usr")
(cd doc/source && PYTHONPATH=$_site sphinx-build -b man -q \
	-D extensions=sphinx.ext.autodoc,sphinx.ext.todo \
	-d "$SRC_ROOT/khal-doctrees" . "$SRC_ROOT/khal-man")
install -Dm644 "$SRC_ROOT/khal-man/khal.1" -t "$PKG/usr/share/man/man1"

# ikhal IS THE ENTRY POINT, and it is the one a menu row wants: `khal` prints
# and exits, `ikhal` is the full-screen calendar a person moves around in.
# Terminal=true and a bare Exec, so the launcher supplies the emulator this
# desktop uses rather than pinning one.
install -d "$PKG/usr/share/applications"
cat > "$PKG/usr/share/applications/ikhal.desktop" <<'EOF'
[Desktop Entry]
Type=Application
Name=Calendar
GenericName=Calendar
Comment=Appointments, over a local vdir
Exec=ikhal
Icon=x-office-calendar
Terminal=true
Categories=Office;Calendar;
Keywords=calendar;appointment;event;ical;khal;
EOF
chmod 644 "$PKG/usr/share/applications/ikhal.desktop"
