#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# IT IS THE RECOVERY PATH FOR A MACHINE THAT WILL NOT POST. With a clip on the
# SPI chip and a cheap CH341 or FT232H, flashrom reads the whole BIOS out and
# writes a known-good one back — which is the only repair for a bad firmware
# update, and the only way to install coreboot. It also reads a router's or an
# embedded board's flash, which is where most reverse engineering starts.
#
# THIS IS THE MOST DESTRUCTIVE PROGRAM IN THE TREE and its own safety is the
# `-p` argument: nothing happens without naming a programmer, and internal
# (this machine's own BIOS) has to be asked for by name. That design is why it
# ships without a wrapper.
#
# `auto` alone is a SOFT selection: a programmer whose library is missing is
# dropped from the binary with one line in the setup summary. The programmers
# this image exists to drive are named after it, which makes each a hard
# selection and setup fails if its library is absent — internal (pciutils),
# the CH341A and dediprog USB clips (libusb), the FT2232/FT232H (libftdi) and
# the SEGGER J-Link (libjaylink).
#
# flashrom(8) is generated by Sphinx from doc/classic_cli_manpage.rst; the HTML
# documentation is off. The version string is the release file's, never a
# `git describe` of whatever work tree the source happens to sit in.
meson setup build \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=lib \
	--buildtype=release \
	-Dprogrammer=auto,internal,ch341a_spi,dediprog,ft2232_spi,jlink_spi \
	-Drpmc=enabled \
	-Dbash_completion=enabled \
	-Duse_git_version=disabled \
	-Dtests=disabled \
	-Dman-pages=enabled \
	-Ddocumentation=disabled
meson compile -C build
DESTDIR=$PKG meson install --no-rebuild -C build
