#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# growisofs, dvd+rw-format and dvd+rw-mediainfo: K3b's DVD and Blu-ray
# writer, blanker and media probe. The Makefile is generated by m4 per `uname
# -s` and appends its own -O2 to the exported flags.
#
# fix-sysmacros-header.patch: growisofs.c calls major()/minor(), which musl
# declares only in sys/sysmacros.h. transport.hxx.patch: the locale buffer is
# sized MB_LEN_MAX, or wctomb() of a multibyte "±" overruns it.
patch -p1 -i "$PORT_SRC/fix-sysmacros-header.patch"
patch -p1 -i "$PORT_SRC/transport.hxx.patch"

make

install -Dm755 growisofs dvd+rw-format dvd+rw-booktype dvd+rw-mediainfo \
	dvd-ram-control -t "$PKG/usr/bin"
install -Dm644 growisofs.1 -t "$PKG/usr/share/man/man1"
