/* ██╗  ██╗██████╗  ██████╗ ███████╗
 * ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
 * █████╔╝ ██║  ██║██║   ██║███████╗
 * ██╔═██╗ ██║  ██║██║   ██║╚════██║
 * ██║  ██╗██████╔╝╚██████╔╝███████║
 * ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
 * ---------------------------------
 *   kdos-find — one question, four places it could be
 *
 *   ╔═ Find in ~/src ══════════════════════════════════════╗
 *   ║ report_                                              ║
 *   ╟──────────────────────────────────────────────────────╢
 *   ║ Applications                                         ║
 *   ║   Reports                                            ║
 *   ║ Recent                                               ║
 *   ║   ~/Documents/report.odt                             ║
 *   ║ Names                                                ║
 *   ║   ~/src/report.c                                     ║
 *   ║ Contents                                             ║
 *   ║   ~/src/notes.md:12: the report is generated by      ║
 *   ╟──────────────────────────────────────────────────────╢
 *   ║ Enter open  Ctrl+G contents  Esc Close               ║
 *   ╚══════════════════════════════════════════════════════╝
 *
 * FOUR SOURCES, AND EACH IS SOMEBODY ELSE'S ANSWER. Applications come from the
 * launcher's own index, recents from `libkxdg`, names from `fd` and contents
 * from `rga` — none of them re-implemented here, because a second walker would
 * disagree with the first about hidden files, ignore rules and symlinks.
 *
 * THE TWO FORKS STREAM, and the fork itself is `filesearch.c`'s, so that this
 * surface and every other one that asks for a file run the same two programs
 * the same way. A search over a home directory is seconds, and a surface that
 * waited for it would be a window that cannot be closed while it is doing the
 * one thing it is for. The child writes into a pipe, the pipe is read in the
 * poll loop, and Escape kills it — the same shape `kdos-status` uses for the
 * tools it runs inside its popup.
 *
 * CONTENTS ARE OPT-IN, on `Ctrl+G`. Names come back in milliseconds and are
 * what somebody usually means; a content search reads every file under the
 * directory, and starting one on every keystroke would be a machine that never
 * stops working.
 *
 * WHAT A RESULT OPENS IS `kdos-appbox open`, which is the one resolution the
 * desktop, the chooser and `mc` all use. A viewer chosen here would be a fifth
 * answer to a question that already has one.
 * ---------------------------------
 */

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "kbase.h"
#include "kwl.h"
#include "kxdg.h"
#include "shell.h"

#include "filesearch.h"

#define FI_COLS 88
#define FI_ROWS 28

/* What one search may put on the screen. A pattern matching everything is the
 * normal case while somebody is still typing it. */
#define FI_MAX_ROWS 400
#define FI_MAX_APPS 8
#define FI_MAX_RECENT 8

enum { G_APPS = 0, G_RECENT, G_NAMES, G_CONTENT, G_N };

static const char *const GROUP[G_N] = {
	"Applications", "Recent", "Names", "Contents"
};

struct row {
	int group;
	char text[512];		/* what is drawn                            */
	char path[PATH_MAX];	/* what Enter opens; empty for a heading    */
	int heading;
};

static struct row rows[FI_MAX_ROWS];
static int nrows, sel, top;

static char query[128];
static int qlen;
static char dir[PATH_MAX];
static char note[192];

/* Which group the running child's lines belong to. */
static int kid_group;
static int content_wanted;

static KtuiKeys keys;

/* ── the row list ──────────────────────────────────────────────────────── */

static void row_add(int group, int heading, const char *text, const char *path)
{
	if (nrows >= FI_MAX_ROWS)
		return;
	struct row *r = &rows[nrows++];

	memset(r, 0, sizeof(*r));
	r->group = group;
	r->heading = heading;
	snprintf(r->text, sizeof(r->text), "%s", text);
	if (path)
		snprintf(r->path, sizeof(r->path), "%s", path);
}

/* `~/x` rather than `/home/me/x`: the home prefix is the same on every row and
 * spends the width the rest of the path needs. */
static const char *pretty(const char *p, char *buf, size_t n)
{
	const char *home = getenv("HOME");
	size_t hl = home ? strlen(home) : 0;

	if (hl > 1 && !strncmp(p, home, hl) && (p[hl] == '/' || !p[hl])) {
		snprintf(buf, n, "~%s", p + hl);
		return buf;
	}
	return p;
}

/* ── what the child sends back ─────────────────────────────────────────── */

/*
 * `fd` prints a path per line; `rga` prints `path:line:text`. Both become a row
 * whose path is the part before the first colon that is a real separator — for
 * `fd` that is the whole line.
 */
static void line_take(const char *line, int tag, void *user)
{
	char buf[PATH_MAX];

	(void)user;
	if (!*line)
		return;
	if (tag == G_NAMES) {
		row_add(G_NAMES, 0, pretty(line, buf, sizeof(buf)), line);
		return;
	}
	{
		char path[PATH_MAX];
		const char *colon = strchr(line, ':');
		char shown[512];

		if (!colon)
			return;
		size_t plen = (size_t)(colon - line);

		if (plen >= sizeof(path))
			return;
		memcpy(path, line, plen);
		path[plen] = '\0';
		snprintf(shown, sizeof(shown), "%s:%s",
			 pretty(path, buf, sizeof(buf)), colon + 1);
		row_add(G_CONTENT, 0, shown, path);
	}
}

/* Nothing is running and the question is not the reason: a surface that drew
 * "nothing" for a machine without the program would blame what was typed. */
static void prog_note(const char *prog)
{
	if (!kb_have_prog(prog))
		snprintf(note, sizeof(note), "%s is not on this machine", prog);
}

/* ── the four searches ─────────────────────────────────────────────────── */

static void search_names(void)
{
	kid_group = G_NAMES;
	sh_fsearch_names(dir, query, G_NAMES, line_take, NULL);
	prog_note("fd");
}

static void search_contents(void)
{
	kid_group = G_CONTENT;
	sh_fsearch_contents(dir, query, G_CONTENT, line_take, NULL);
	prog_note("rga");
}

/*
 * The two sources that answer at once, rebuilt on every keystroke. The forks
 * are not: they are started when the question is finished, because a child per
 * keystroke is a machine that spends its life starting and killing searches.
 */
static void search_local(void)
{
	const struct sh_app *hit[FI_MAX_APPS];
	char recents[FI_MAX_RECENT * 4][512];
	char buf[PATH_MAX];
	int n;

	nrows = 0;
	sel = 0;
	top = 0;
	if (!qlen)
		return;

	n = sh_apps_match(query, hit, FI_MAX_APPS);
	if (n > 0) {
		row_add(G_APPS, 1, GROUP[G_APPS], NULL);
		for (int i = 0; i < n; i++)
			row_add(G_APPS, 0, hit[i]->name, hit[i]->id);
	}

	n = kxdg_recent_all(recents, FI_MAX_RECENT * 4);
	int shown = 0;
	for (int i = 0; i < n && shown < FI_MAX_RECENT; i++) {
		if (!strcasestr(recents[i], query))
			continue;
		if (!shown)
			row_add(G_RECENT, 1, GROUP[G_RECENT], NULL);
		row_add(G_RECENT, 0, pretty(recents[i], buf, sizeof(buf)),
			recents[i]);
		shown++;
	}
}

/* The cursor sits on a RESULT, never on a group name: a heading is not
 * something Enter can open, and a list whose first row cannot be chosen teaches
 * that Enter does nothing. */
static void sel_fix(void)
{
	if (sel >= nrows)
		sel = nrows ? nrows - 1 : 0;
	if (sel < 0)
		sel = 0;
	while (sel < nrows && rows[sel].heading)
		sel++;
	if (sel >= nrows)
		sel = nrows ? nrows - 1 : 0;
}

/* Heading rows are inserted when the first line of a group arrives, so a group
 * that answers nothing draws nothing at all. */
static void headings_fix(void)
{
	for (int g = G_NAMES; g <= G_CONTENT; g++) {
		int have = 0, head = 0;

		for (int i = 0; i < nrows; i++)
			if (rows[i].group == g)
				rows[i].heading ? (head = 1) : (have = 1);
		if (!have || head)
			continue;
		/* Insert the heading before the group's first row. */
		int at = 0;

		while (at < nrows && rows[at].group != g)
			at++;
		if (nrows >= FI_MAX_ROWS)
			return;
		memmove(&rows[at + 1], &rows[at],
			sizeof(rows[0]) * (size_t)(nrows - at));
		nrows++;
		memset(&rows[at], 0, sizeof(rows[at]));
		rows[at].group = g;
		rows[at].heading = 1;
		snprintf(rows[at].text, sizeof(rows[at].text), "%s", GROUP[g]);
	}
}

/* ── opening one ───────────────────────────────────────────────────────── */

static void open_sel(void)
{
	if (sel < 0 || sel >= nrows || rows[sel].heading || !rows[sel].path[0])
		return;
	if (rows[sel].group == G_APPS) {
		/*
		 * AN APPLICATION IS ITS Exec LINE, resolved again here rather
		 * than kept in the row: the entry's `Exec` already reads
		 * `kdos-appbox run <command>` for a boxed app, and its ID is
		 * not that command — handing the ID to `run` asks the box for
		 * a program of that name and starts nothing at all. The
		 * launcher runs it the same way, and `Terminal=true` is a
		 * program with no window of its own.
		 */
		const struct sh_app *a = sh_apps_find(rows[sel].path);
		const char *argv[32];
		char id[160], buf[SH_APP_EXEC], *save = NULL;
		int n = 0;

		if (!a)
			return;
		if (a->terminal)
			n = sh_term_argv_in(a->term, a->floating, a->size,
					    argv, n, 32, a->exec, id,
					    sizeof(id));
		snprintf(buf, sizeof(buf), "%s", a->exec);
		for (char *tok = strtok_r(buf, " \t", &save);
		     tok && n < 30; tok = strtok_r(NULL, " \t", &save))
			argv[n++] = tok;
		if (!n)
			return;
		argv[n] = NULL;
		sh_spawn(argv);
		return;
	}
	{
		const char *argv[] = { "kdos-appbox", "open", rows[sel].path,
				       NULL };

		sh_spawn(argv);
	}
}

/* ── the frame ─────────────────────────────────────────────────────────── */

static void draw(void)
{
	int w = ktui_w, h = ktui_h;
	int list_top = 3;
	int list_rows = h - list_top - 3;
	char title[320];
	char buf[PATH_MAX];

	if (w < 24 || h < 10)
		return;
	if (list_rows < 1)
		list_rows = 1;

	snprintf(title, sizeof(title), "Find in %s",
		 pretty(dir, buf, sizeof(buf)));
	ktui_draw_fill(krect(0, 0, w, h), KT_SURFACE);
	ktui_draw_box(krect(0, 0, w, h), title, KT_ACCENT, KT_SURFACE, 1);

	/* The question, with the cursor as a block after it: a field with no
	 * cursor is a label, and a person cannot tell it takes typing. */
	ktui_draw_fill(krect(1, 1, w - 2, 1), KT_SURFACE);
	ktui_draw_text(2, 1, w - 5, query, KT_TEXT, KT_SURFACE, KT_A_NONE);
	{
		int cx = 2 + ktui_utf8_width(query);

		if (cx < w - 2)
			ktui_draw_text(cx, 1, 1, ktui_glyph[KT_G_FULL],
				       KT_ACCENT, KT_SURFACE, KT_A_NONE);
	}
	ktui_draw_hline(1, 2, w - 2, KT_G_HL, KT_DIM, KT_SURFACE);

	if (sel < top)
		top = sel;
	if (sel >= top + list_rows)
		top = sel - list_rows + 1;

	if (!nrows) {
		const char *msg = qlen ? (sh_fsearch_fd() >= 0 ? "searching…"
							      : "nothing")
				       : "Type what you are looking for";

		ktui_draw_text((w - (int)strlen(msg)) / 2, h / 2, w - 2, msg,
			       KT_MID, KT_SURFACE, KT_A_NONE);
	}

	for (int i = 0; i < list_rows && top + i < nrows; i++) {
		const struct row *r = &rows[top + i];
		int y = list_top + i, on = top + i == sel && !r->heading;
		int bg = on ? KT_ACCENT : KT_SURFACE;
		int fg = on ? KT_SURFACE : KT_TEXT;

		ktui_draw_fill(krect(1, y, w - 2, 1), bg);
		if (r->heading)
			ktui_draw_text(2, y, w - 4, r->text, KT_MID,
				       KT_SURFACE, KT_A_NONE);
		else
			ktui_draw_text(4, y, w - 6, r->text, fg, bg,
				       KT_A_NONE);
	}

	ktui_draw_hline(1, h - 3, w - 2, KT_G_HL, KT_DIM, KT_SURFACE);
	if (note[0]) {
		ktui_hint_row(&keys, krect(0, h - 2, 0, 0), KT_SURFACE);
		ktui_draw_text(2, h - 2, w - 4, note, KT_WARN, KT_SURFACE,
			       KT_A_NONE);
	} else {
		ktui_hint_if(nrows > 0, "Enter", "open");
		ktui_hint_if(!content_wanted, "Ctrl+G", "contents");
		ktui_hint("Esc", ktui_esc_verb(&keys));
		ktui_hint_row(&keys, krect(2, h - 2, w - 4, 1), KT_SURFACE);
	}
	ktui_draw_flush();
}

/* ── the program ───────────────────────────────────────────────────────── */

/* Start the file searches for the question as it now stands. */
static void search_files(void)
{
	if (!qlen) {
		sh_fsearch_stop();
		return;
	}
	note[0] = '\0';
	search_names();
}

int find_main(int argc, char **argv)
{
	const char *font = NULL;
	const char *want_dir = NULL;
	int dump = 0;

	for (int i = 1; i < argc; i++) {
		if (!strcmp(argv[i], "--font") && i + 1 < argc)
			font = argv[++i];
		else if (!strcmp(argv[i], "--dump"))
			dump = 1;
		else if (!strcmp(argv[i], "--query") && i + 1 < argc)
			snprintf(query, sizeof(query), "%s", argv[++i]);
		else if (argv[i][0] == '-') {
			fprintf(stderr, "usage: kdos-find [--font NAME] "
					"[--query TEXT] [--dump] [DIR]\n");
			return 2;
		} else if (!want_dir) {
			want_dir = argv[i];
		}
	}
	qlen = (int)strlen(query);

	/* The directory the verb named, else home: a search with no root is a
	 * search of the filesystem, which is not what "Find Here" means and is
	 * not what a chord with no context should start either. */
	if (!want_dir || !realpath(want_dir, dir)) {
		const char *home = getenv("HOME");

		snprintf(dir, sizeof(dir), "%s", home && *home ? home : "/");
	}

	sh_apps_load();
	search_local();

	KDispConfig cfg = {
		.role = KDISP_ROLE_TOPLEVEL,
		.cols = FI_COLS,
		.rows = FI_ROWS,
		.app_id = "kdos-find",
		.font = font,
		.keyboard = 1,
	};

	sh_theme_from_cache();
	if (dump) {
		ktui_offscreen_init(FI_COLS, FI_ROWS);
		ktui_draw_init();
		draw();
		ktui_draw_dump();
		return 0;
	}
	if (kdisp_init(&cfg, kdos_disp, kdos_disp_n) != 0) {
		fprintf(stderr, "kdos-find: no display server\n");
		return 1;
	}
	ktui_draw_init();
	if (qlen)
		search_files();

	while (!kdisp_should_close()) {
		/* Names first, then contents if they were asked for: two
		 * children at once would interleave their lines into one
		 * list. */
		if (sh_fsearch_fd() >= 0 && !sh_fsearch_poll() &&
		    kid_group == G_NAMES && content_wanted)
			search_contents();
		headings_fix();
		sel_fix();
		draw();

		KtuiEvent ev;

		/* A short wait while a child is running, so its lines arrive
		 * as it finds them rather than a second at a time. */
		if (!ktui_backend()->poll_event(&ev,
						sh_fsearch_fd() >= 0 ? 100
								     : 1000)) {
			if (ktui_resized) {
				ktui_resized = 0;
				ktui_draw_resize();
				ktui_draw_invalidate();
			}
			continue;
		}
		if (ev.type != KT_EVT_KEY)
			continue;

		{
			int r = ktui_keys(&keys, &ev);

			if (r == KTUI_KEY_CLOSE)
				break;
			if (r == KTUI_KEY_TAKEN)
				continue;
		}

		switch (ev.key) {
		case KT_K_UP:
			while (sel > 0)
				if (!rows[--sel].heading)
					break;
			break;
		case KT_K_DOWN:
			while (sel + 1 < nrows)
				if (!rows[++sel].heading)
					break;
			break;
		case KT_K_HOME:
			sel = 0;
			break;
		case KT_K_END:
			sel = nrows ? nrows - 1 : 0;
			break;
		case KT_K_PGUP:
			sel -= ktui_h - 6;
			if (sel < 0)
				sel = 0;
			break;
		case KT_K_PGDN:
			sel += ktui_h - 6;
			if (sel >= nrows)
				sel = nrows ? nrows - 1 : 0;
			break;
		case KT_K_ENTER:
			open_sel();
			break;
		case KT_K_BACKSPACE:
			if (qlen > 0)
				query[--qlen] = '\0';
			search_local();
			search_files();
			break;
		default:
			if ((ev.mods & KT_MOD_CTRL) && (ev.key == 'g' ||
							ev.key == 'G')) {
				/* Asked for once, and it then follows every
				 * later question: somebody who wants contents
				 * wants them for the next word too. */
				content_wanted = 1;
				if (qlen && sh_fsearch_fd() < 0)
					search_contents();
				break;
			}
			if (ev.mods & (KT_MOD_CTRL | KT_MOD_ALT))
				break;
			if (ev.key >= 0x20 && ev.key < 0x7f &&
			    qlen < (int)sizeof(query) - 1) {
				query[qlen++] = (char)ev.key;
				query[qlen] = '\0';
				search_local();
				search_files();
			}
			break;
		}
	}

	sh_fsearch_stop();
	kdisp_shutdown();
	return 0;
}
