/* ██╗  ██╗██████╗  ██████╗ ███████╗
 * ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
 * █████╔╝ ██║  ██║██║   ██║███████╗
 * ██╔═██╗ ██║  ██║██║   ██║╚════██║
 * ██║  ██╗██████╔╝╚██████╔╝███████║
 * ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
 * ---------------------------------
 *   The KDOS logo, as cells
 *
 * `/usr/share/kdos/logo.txt` is generated by `genlogo.py` and is what
 * `kdos-banner` replays on the login banner, so it carries SGR colour: the
 * banner writes it to a terminal a raster line at a time and lets the terminal
 * do the colouring.
 *
 * A surface cannot. Painting those escapes into cells puts `[1;32m` on the
 * screen as text and makes every width measurement wrong by the length of the
 * escapes, so the colour is stripped rather than translated — this desktop's
 * palette is libktui's eight slots and the caller picks one.
 *
 * TWO SURFACES DRAW IT and there is one loader: the screensaver bounces it and
 * the About surface stands it in a column. A second copy is a second answer to
 * how wide the artwork is, and the width is what both of them centre on.
 * ---------------------------------
 */

#include <stdio.h>
#include <string.h>

#include "ktui.h"
#include "shell.h"

static void strip_ansi(char *s)
{
	char *w = s;

	for (const char *r = s; *r; ) {
		if (*r != '\033') {
			*w++ = *r++;
			continue;
		}
		r++;
		if (*r == '[') {
			r++;
			/* CSI runs until a final byte in 0x40..0x7e. */
			while (*r && (unsigned char)*r < 0x40)
				r++;
			if (*r)
				r++;
		} else if (*r) {
			r++;	/* a two-byte escape; nothing here emits one */
		}
	}
	*w = '\0';
}

int sh_logo_load(const char *path, char (*out)[SH_LOGO_BYTES], int max,
		 int *nlines, int *width)
{
	FILE *f = fopen(path, "r");
	char line[SH_LOGO_BYTES];
	int n = 0, w = 0;

	*nlines = 0;
	*width = 0;
	if (!f)
		return -1;
	while (n < max && fgets(line, sizeof(line), f)) {
		line[strcspn(line, "\r\n")] = '\0';
		strip_ansi(line);
		snprintf(out[n], SH_LOGO_BYTES, "%s", line);

		int lw = ktui_utf8_width(out[n]);

		if (lw > w)
			w = lw;
		n++;
	}
	fclose(f);
	/* Trailing blank lines are dropped: they would bounce the saver's logo
	 * off the bottom edge early, with a gap under it nobody can see the
	 * reason for, and they would pad the About column the same way. */
	while (n > 0 && !out[n - 1][0])
		n--;
	*nlines = n;
	*width = w;
	return n > 0 ? 0 : -1;
}
