#!/usr/bin/env python3
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝  ╚═════╝ ╚═════╝ ╚══════╝
# ---------------------------------
#   vendor.py — Alpine's security database, pruned into one table
#
# HOST-ONLY, run by hand with network. Nothing on the target and nothing in the
# build ever runs this; what ships is `secdb.txt` beside it, which is committed.
# Same shape as kdos-icons' and kdos-cursors' vendoring, and for the same
# reasons: the prune is a KDOS decision, and the artefact is diffable.
#
# WHY ALPINE. It is the closest distro to KDOS that publishes a machine-readable
# security database: musl, the same upstream tarballs, comparable pins. OSV's
# `Alpine/all.zip` carries the same facts in a heavier form, and NVD is retired
# feeds plus an API — neither answers a question this 270 KB file cannot.
#
# WHAT IT IS NOT. secdb is keyed to ALPINE package names and Alpine's own
# versioning, so a match is a strong hint and never a proof: a port whose name
# differs needs `secdb = <alpine-name>` in its recipe, and a CVE fixed upstream
# in a version Alpine never shipped is invisible here. There is no reliable
# mapping from a source tarball name to CVEs — cve-bin-tool's CPE lookups need a
# human to assert `zlib -> cpe:2.3:a:zlib:zlib` — so this tool reports what
# Alpine recorded and says so.
#
#   usage: vendor.py [branch ...]      (default: the six newest stable branches)
#
# The output is one line per (package, fixed version):
#
#   <alpine-package> <fixed-version> <CVE>[,<CVE>...]
#
# and `kdos cve` reads it with no JSON parser at all.

import json
import sys
import urllib.request
from datetime import datetime, timezone

BASE = "https://secdb.alpinelinux.org"
DEFAULT_BRANCHES = ["v3.19", "v3.20", "v3.21", "v3.22", "v3.23", "v3.24"]
REPOS = ("main", "community")


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read()


def main(argv):
    branches = argv[1:] or DEFAULT_BRANCHES
    merged = {}
    got = []

    for branch in branches:
        for repo in REPOS:
            url = f"{BASE}/{branch}/{repo}.json"
            try:
                data = json.loads(fetch(url))
            except Exception as e:               # noqa: BLE001 — report and go on
                print(f"  {branch}/{repo}: {e}", file=sys.stderr)
                continue
            got.append(f"{branch}/{repo}")
            for entry in data.get("packages", []):
                pkg = entry.get("pkg") or {}
                name = pkg.get("name")
                if not name:
                    continue
                fixes = merged.setdefault(name, {})
                for version, cves in (pkg.get("secfixes") or {}).items():
                    fixes.setdefault(version, set()).update(cves)

    if not merged:
        print("nothing fetched — refusing to overwrite secdb.txt", file=sys.stderr)
        return 1

    # Every branch is merged rather than kept separate: a CVE fixed in v3.19 is
    # still a CVE, and a KDOS pin older than that fix is still exposed. The union
    # is what makes an old pin visible at all.
    lines = []
    for name in sorted(merged):
        for version in sorted(merged[name]):
            cves = ",".join(sorted(merged[name][version]))
            lines.append(f"{name} {version} {cves}")

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    header = (
        "# KDOS security database — GENERATED by vendor.py; do not edit.\n"
        f"# generated {stamp} from Alpine secdb: {' '.join(got)}\n"
        "# source https://secdb.alpinelinux.org/ (CC-BY-SA-4.0)\n"
        "# <alpine-package> <version-that-fixed-it> <CVE>[,<CVE>...]\n"
    )
    out = header + "\n".join(lines) + "\n"
    with open("secdb.txt", "w") as f:
        f.write(out)
    print(f"secdb.txt: {len(merged)} packages, {len(lines)} rows, {len(out)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
