#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# IT IS THE RECOVERY PATH FOR A MACHINE THAT WILL NOT POST. With a clip on the
# SPI chip and a cheap CH341 or FT232H, flashrom reads the whole BIOS out and
# writes a known-good one back — which is the only repair for a bad firmware
# update, and the only way to install coreboot. It also reads a router's or an
# embedded board's flash, which is where most reverse engineering starts.
#
# THIS IS THE MOST DESTRUCTIVE PROGRAM IN THE TREE and its own safety is the
# `-p` argument: nothing happens without naming a programmer, and internal
# (this machine's own BIOS) has to be asked for by name. That design is why it
# ships without a wrapper.
meson setup build \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=lib \
	--buildtype=release \
	-Dprogrammer=auto \
	-Dtests=disabled \
	-Dman-pages=disabled \
	-Ddocumentation=disabled
meson compile -C build
DESTDIR=$PKG meson install --no-rebuild -C build

# SINCE 1.6.0 THE MAN PAGE IS GENERATED BY SPHINX, which is a dozen python
# ports for one roff file. The reStructuredText it is generated FROM is in the
# tarball and reads perfectly well in a pager, so the manual ships as that
# rather than not at all — this is the most destructive program in the tree
# and its documentation is not optional.
install -Dm644 doc/classic_cli_manpage.rst \
	"$PKG/usr/share/doc/flashrom/flashrom.rst"
