#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# IT IS THE RECOVERY PATH FOR A MACHINE THAT WILL NOT POST. With a clip on the
# SPI chip and a cheap CH341 or FT232H, flashrom reads the whole BIOS out and
# writes a known-good one back — which is the only repair for a bad firmware
# update, and the only way to install coreboot. It also reads a router's or an
# embedded board's flash, which is where most reverse engineering starts.
#
# THIS IS THE MOST DESTRUCTIVE PROGRAM IN THE TREE and its own safety is the
# `-p` argument: nothing happens without naming a programmer, and internal
# (this machine's own BIOS) has to be asked for by name. That design is why it
# ships without a wrapper.
#
# flashrom(8) is generated by Sphinx from doc/classic_cli_manpage.rst; the HTML
# documentation is off.
meson setup build \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=lib \
	--buildtype=release \
	-Dprogrammer=auto \
	-Dtests=disabled \
	-Dman-pages=enabled \
	-Ddocumentation=disabled
meson compile -C build
DESTDIR=$PKG meson install --no-rebuild -C build
