#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

# Alpine's patches, for musl: fpos_t and the 64-bit file calls are glibc
# shapes (fix-musl-incompability, lfs64), headers that GCC 13 and 15 stop
# pulling in transitively (gcc13, gcc15-musl), and the page size queried at
# run time rather than from a macro musl does not define (dyn-pagesize).
for _p in fix-musl-incompability gcc13 lfs64 gcc15-musl dyn-pagesize; do
	patch -p1 -i "$PORT_SRC/$_p.patch"
done

# A source is beside the recipe after `make fetch`, or in kpkg's source
# directory on a machine that rebuilds from its own cache.
_src() {
	if [ -f "$PORT_SRC/$1" ]; then echo "$PORT_SRC/$1"; else echo "$SOURCE_DIR/$1"; fi
}

# THE PYTHON ADD-ON BINDINGS ARE GENERATED BY A GROOVY SCRIPT, run on the
# OpenJDK at build time. Groovy and the two Apache Commons jars it needs are
# upstream's release archives; they run only in the build and none of them
# reaches $PKG. Given their directories, the build does not try to download
# them.
python3 -m zipfile -e "apache-groovy-binary-$_groovy.zip" "$SRC_ROOT/groovy"
_groovydir="$SRC_ROOT/groovy/groovy-$_groovy"

# EVERY LIBRARY KODI WOULD FETCH IS GIVEN AS A LOCAL ARCHIVE, and each is
# checked against the hash in Kodi's own VERSION file:
#   - crossguid, fstrcmp and flatbuffers (headers and the flatc tool) are not
#     ports;
#   - FFmpeg 6.0: Kodi 21 needs libpostproc and the FFmpeg 6 API, and the
#     ffmpeg port is newer than both; its https input links GnuTLS when the
#     probe finds it, so gnutls is in depends;
#   - fmt 9 and spdlog 1.10: Kodi 21 does not build against the fmt 12 the
#     fmt port carries, and an internal fmt forces an internal spdlog;
#   - TinyXML2 and PCRE (the 8.x API, pcrecpp) are not ports;
#   - Kodi's own forks of libdvdcss, libdvdread and libdvdnav, which the
#     DVD player is written against.
# Every one is compiled from that source and linked in statically.
#
# The Wayland windowing system with OpenGL ES through EGL, VA-API decoding.
# The optional libraries are all named, each being quietly dropped when
# missing: ALSA, PulseAudio and PipeWire output, Avahi (Zeroconf), BlueZ,
# Blu-ray, DBus, libcap, LCMS2, dav1d, the web server (libmicrohttpd), plist
# (AirPlay), Samba shares, udev, udfread, XSLT, HDMI-CEC (libcec), NFS
# shares (libnfs), AirTunes (shairplay), ISO9660++ (libcdio's C++ binding)
# and the LIRC client. libcec and libnfs are taken from their ports, never
# built from Kodi's pinned copies. sndio, MariaDB and MySQL are off. Event
# clients and the test suite are off.
#
# The SIMD level is fixed at SSE2, the x86-64 baseline. Left alone, the
# build reads the builder's /proc/cpuinfo and turns on SSE4.1 for every
# machine the package later runs on.
#
# musl gives a thread 128 KiB of stack unless the executable asks for more,
# and Kodi's threads overrun that; the linker note raises it to 2 MiB.
export LDFLAGS="$LDFLAGS -Wl,-z,stack-size=2097152"
mkdir build && cd build
cmake .. -G Ninja \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DCORE_PLATFORM_NAME=wayland \
	-DAPP_RENDER_SYSTEM=gles \
	-DENABLE_VAAPI=ON \
	-DENABLE_VDPAU=OFF \
	-DENABLE_GOLD=OFF \
	-DENABLE_LLD=OFF \
	-DENABLE_MOLD=OFF \
	-DUSE_LTO=OFF \
	-DENABLE_SSE=ON \
	-DENABLE_SSE2=ON \
	-DENABLE_SSE3=OFF \
	-DENABLE_SSSE3=OFF \
	-DENABLE_SSE4_1=OFF \
	-DENABLE_SSE4_2=OFF \
	-DENABLE_AVX=OFF \
	-DENABLE_AVX2=OFF \
	-DENABLE_TESTING=OFF \
	-DENABLE_EVENTCLIENTS=OFF \
	-DENABLE_PYTHON=ON \
	-DENABLE_UPNP=ON \
	-DENABLE_OPTICAL=ON \
	-DENABLE_DVDCSS=ON \
	-DENABLE_AIRTUNES=ON \
	-DENABLE_ALSA=ON \
	-DENABLE_PULSEAUDIO=ON \
	-DENABLE_PIPEWIRE=ON \
	-DENABLE_AVAHI=ON \
	-DENABLE_BLUETOOTH=ON \
	-DENABLE_BLURAY=ON \
	-DENABLE_CAP=ON \
	-DENABLE_DAV1D=ON \
	-DENABLE_DBUS=ON \
	-DENABLE_LCMS2=ON \
	-DENABLE_MICROHTTPD=ON \
	-DENABLE_PLIST=ON \
	-DENABLE_SMBCLIENT=ON \
	-DENABLE_UDEV=ON \
	-DENABLE_UDFREAD=ON \
	-DENABLE_XSLT=ON \
	-DENABLE_CEC=ON \
	-DENABLE_NFS=ON \
	-DENABLE_ISO9660PP=ON \
	-DENABLE_LIRCCLIENT=ON \
	-DENABLE_MDNS=OFF \
	-DENABLE_SNDIO=OFF \
	-DENABLE_MARIADBCLIENT=OFF \
	-DENABLE_MYSQLCLIENT=OFF \
	-DENABLE_INTERNAL_FFMPEG=ON \
	-DENABLE_INTERNAL_DAV1D=OFF \
	-DENABLE_INTERNAL_CROSSGUID=ON \
	-DENABLE_INTERNAL_CEC=OFF \
	-DENABLE_INTERNAL_NFS=OFF \
	-DENABLE_INTERNAL_FLATBUFFERS=ON \
	-DENABLE_INTERNAL_FMT=ON \
	-DENABLE_INTERNAL_SPDLOG=ON \
	-DENABLE_INTERNAL_TINYXML2=ON \
	-DENABLE_INTERNAL_FSTRCMP=ON \
	-DENABLE_INTERNAL_PCRE=ON \
	-DENABLE_INTERNAL_RapidJSON=OFF \
	-DENABLE_INTERNAL_TAGLIB=OFF \
	-DENABLE_INTERNAL_UDFREAD=OFF \
	-DENABLE_INTERNAL_KISSFFT=ON \
	-DENABLE_INTERNAL_GTEST=OFF \
	-DCROSSGUID_URL="$(_src "crossguid-$_crossguid.tar.gz")" \
	-DLIBDVDCSS_URL="$(_src "libdvdcss-$_dvdcss.tar.gz")" \
	-DLIBDVDNAV_URL="$(_src "libdvdnav-$_dvdnav.tar.gz")" \
	-DLIBDVDREAD_URL="$(_src "libdvdread-$_dvdread.tar.gz")" \
	-DFFMPEG_URL="$(_src "ffmpeg-$_ffmpeg.tar.gz")" \
	-DFMT_URL="$(_src "fmt-$_fmt.tar.gz")" \
	-DSPDLOG_URL="$(_src "spdlog-$_spdlog.tar.gz")" \
	-DTINYXML2_URL="$(_src "tinyxml2-$_tinyxml2.tar.gz")" \
	-DFLATBUFFERS_URL="$(_src "flatbuffers-$_flatbuf.tar.gz")" \
	-DFSTRCMP_URL="$(_src "fstrcmp-$_fstrcmp.tar.gz")" \
	-DPCRE_URL="$(_src "pcre-$_pcre.tar.bz2")" \
	-Dgroovy_SOURCE_DIR="$_groovydir" \
	-Dapache-commons-lang_SOURCE_DIR="$SRC_ROOT/commons-lang3-$_langver" \
	-Dapache-commons-text_SOURCE_DIR="$SRC_ROOT/commons-text-$_textver" \
	-Wno-dev
# The static libcrossguid.a is not a tracked output of its external project,
# so a parallel build can reach the link before it exists. Build it first.
ninja crossguid
ninja
DESTDIR=$PKG ninja install
cd ..

# No display manager reads a session file, and no firewalld reads a service
# definition.
rm -rf "$PKG/usr/share/xsessions" "$PKG/usr/share/wayland-sessions" \
	"$PKG/usr/lib/firewalld"

# ADD-ON UPDATES DEFAULT TO NEVER. Left at upstream's default, Kodi contacts
# its add-on repository at every start to look for updates. appliance.xml is
# the settings file Kodi reads last, for exactly this kind of override; the
# user can still turn updates on in Settings > System > Add-ons.
install -Dm644 /dev/stdin "$PKG/usr/share/kodi/system/settings/appliance.xml" <<'XML'
<?xml version="1.0" encoding="utf-8" ?>
<settings version="1">
  <section id="system">
    <category id="addons">
      <group id="1">
        <setting id="general.addonupdates">
          <default>2</default>
        </setting>
      </group>
    </category>
  </section>
</settings>
XML

# UPSTREAM'S ENTRY IS REPLACED for StartupWMClass: the Wayland app_id is
# Kodi's application name, Kodi.
cat > "$PKG/usr/share/applications/kodi.desktop" <<'DESKTOP'
[Desktop Entry]
Type=Application
Name=Kodi
GenericName=Media Center
Comment=Watch and listen to your videos, music and pictures
TryExec=kodi
Exec=kodi
Icon=kodi
Terminal=false
StartupWMClass=Kodi
Categories=AudioVideo;Video;Player;TV;
Keywords=kodi;xbmc;media;center;tv;movies;music;player;
Actions=Fullscreen;

[Desktop Action Fullscreen]
Name=Open in Full Screen
Exec=kodi -fs
DESKTOP
chmod 644 "$PKG/usr/share/applications/kodi.desktop"
