#!/bin/bash


tar xf $PORT_SRC/${name}-vendor-${version}.tar.xz

# A BACKUP TOOL IS ONE STATIC BINARY OR IT IS NOT A BACKUP TOOL. The repository
# has to be restorable from a machine that is not this one — a rescue stick, a
# borrowed laptop — and anything needing a python or a shared library at
# restore time fails at exactly the moment it is needed. CGO_ENABLED=0 is what
# makes that true.
export CGO_ENABLED=0
go build -mod=vendor -ldflags "-s -w -X main.version=$version" -o restic ./cmd/restic
install -Dm755 restic $PKG/usr/bin/restic

# The man pages and completions are GENERATED BY THE BINARY rather than
# shipped, so they cannot go stale against the version installed.
install -dm755 $PKG/usr/share/man/man1
./restic generate --man $PKG/usr/share/man/man1
./restic generate --bash-completion $PKG/usr/share/bash-completion/completions/restic
