#!/bin/bash
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------

tar xf $PORT_SRC/${name}-vendor-${version}.tar.xz

# A BACKUP TOOL IS ONE STATIC BINARY OR IT IS NOT A BACKUP TOOL. The repository
# has to be restorable from a machine that is not this one — a rescue stick, a
# borrowed laptop — and anything needing a python or a shared library at
# restore time fails at exactly the moment it is needed. CGO_ENABLED=0 is what
# makes that true.
export CGO_ENABLED=0
go build -mod=vendor -ldflags "-s -w -X main.version=$version" -o restic ./cmd/restic
install -Dm755 restic $PKG/usr/bin/restic

# The man pages and completions are GENERATED BY THE BINARY rather than
# shipped, so they cannot go stale against the version installed.
# `generate` WRITES A FILE, it does not create the directory above it — the man
# target is a directory that is made here and the completion target is a FILE
# whose parent is not, so the second call fails with "no such file or
# directory" naming the file it was about to write.
install -dm755 $PKG/usr/share/man/man1
install -dm755 $PKG/usr/share/bash-completion/completions
install -dm755 $PKG/usr/share/zsh/site-functions

./restic generate --man $PKG/usr/share/man/man1
./restic generate --bash-completion $PKG/usr/share/bash-completion/completions/restic
./restic generate --zsh-completion $PKG/usr/share/zsh/site-functions/_restic
