#!/usr/bin/env python3
# ██╗  ██╗██████╗  ██████╗ ███████╗
# ██║ ██╔╝██╔══██╗██╔═══██╗██╔════╝
# █████╔╝ ██║  ██║██║   ██║███████╗
# ██╔═██╗ ██║  ██║██║   ██║╚════██║
# ██║  ██╗██████╔╝╚██████╔╝███████║
# ╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚══════╝
# ---------------------------------
#   KD's Homebrew Linux Distro
# ---------------------------------
#
# Cuts kdos-logo-mono.pbm from kdos.png for the kernel's panic screen.
#
# HOST-ONLY, like kdos-icons/genmarks.py: it needs PIL, nothing on the target
# or in the build container runs it, and the .pbm it produces is COMMITTED.
# The kernel build reads that file and never this script.
#
#   ports/core/linux/genlogo-mono.py [kdos.png] [out.pbm]
#
# Three things are deliberate:
#
#   - Crop at the GLOW alpha threshold, not the solid one. Cropping at solid
#     clips the mascot's outer glow and the silhouette comes out lopsided —
#     the same trap genmarks.py documents.
#   - The WORDMARK is dropped. At the size drm_panic draws a logo (1:1 pixels,
#     ~80 rows) five letters are illegible mush, so only the penguin is cut.
#     The split is found by scanning for the thinnest row between 68% and 85%
#     of the mark's height, because the penguin's feet and the K overlap
#     horizontally and there is no fully empty band to look for.
#   - Ink is the mascot's DARK line art inside the silhouette, not the
#     silhouette itself. A solid silhouette at this size is a black blob with
#     no face; the outline keeps the eyes and the beak.
#
# P1 (ASCII) rather than P4 so the committed artefact diffs in git. The
# kernel's pnmtologo reads both.

import sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "kdos.png"
OUT = sys.argv[2] if len(sys.argv) > 2 else "ports/core/linux/kdos-logo-mono.pbm"

GLOW_ALPHA = 40		# crop threshold — the glow, not the solid body
INSIDE = 110		# resampled mask: still part of the mark
INK = 95		# luminance below this, inside the mark, is ink
HEIGHT = 80		# rows; drm_panic draws 1:1, so this is real pixels

im = Image.open(SRC).convert("RGBA")
mask = im.split()[3].point(lambda v: 255 if v > GLOW_ALPHA else 0)
bb = mask.getbbox()
if not bb:
    sys.exit("genlogo-mono: the source image is fully transparent")

im, mask = im.crop(bb), mask.crop(bb)
w, h = mask.size

rows = [sum(1 for x in range(w) if mask.getpixel((x, y))) for y in range(h)]
split = min(range(int(h * 0.68), int(h * 0.85)), key=lambda y: rows[y])
im, mask = im.crop((0, 0, w, split)), mask.crop((0, 0, w, split))

width = max(1, round(im.width * HEIGHT / im.height))
lum = im.resize((width, HEIGHT), Image.LANCZOS).convert("L")
sil = mask.resize((width, HEIGHT), Image.LANCZOS)

bits = [
    [
        1 if sil.getpixel((x, y)) > INSIDE and lum.getpixel((x, y)) < INK else 0
        for x in range(width)
    ]
    for y in range(HEIGHT)
]

with open(OUT, "w") as f:
    f.write("P1\n")
    f.write("# KDOS panic-screen mark — generated by genlogo-mono.py, do not edit\n")
    f.write(f"{width} {HEIGHT}\n")
    for row in bits:
        f.write("".join(str(b) for b in row) + "\n")

ink = sum(sum(r) for r in bits)
print(f"genlogo-mono: {OUT} {width}x{HEIGHT}, {ink} ink px "
      f"({100 * ink / (width * HEIGHT):.0f}%)")
